# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:20-bullseye-slim

# Install yt-dlp
RUN apt-get update \
    && apt-get install -y python3-pip python3 \
    && pip3 install yt-dlp \
    && rm -rf /var/lib/apt/lists/*

# Create app directory and downloads dir
WORKDIR /app
RUN mkdir -p /root/Downloads

# Copy package and source
COPY package.json package-lock.json tsconfig.json ./
COPY src ./src

# Install dependencies and build
RUN npm ci --ignore-scripts \
    && npm run prepare \
    && npm prune --production

# Default command
ENTRYPOINT ["node", "lib/index.mjs"]
